import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Defaultwrapper from '@/components/defaultwrapper'
import HomePage from '@/components/home'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
     <Head>
        <title>SLOTTO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Jost:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>
      </Head>
      <Defaultwrapper>
        <HomePage />
      </Defaultwrapper>
    </>
  )
}
